.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kakobit_qt test_kakobit_qt
clean: FORCE
	$(MAKE) -C .. kakobit_qt_clean test_kakobit_qt_clean
check: FORCE
	$(MAKE) -C .. test_kakobit_qt_check
kakobit-qt kakobit-qt.exe: FORCE
	 $(MAKE) -C .. kakobit_qt
