.TH KAKOBIT-CLI "1" "February 2016" "kakobit-cli 0.12"
.SH NAME
kakobit-cli \- a remote procedure call client for Kakobit Core. 
.SH SYNOPSIS
kakobit-cli [options] <command> [params] \- Send command to Kakobit Core. 
.TP
kakobit-cli [options] help \- Asks Kakobit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the kakobit-cli program. kakobit-cli is an RPC client used to send commands to Kakobit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBkakobitd\fP, \fBkakobit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
